Use a config file to store ui config
revault/revault-gui pull request #120
Opened 2021-05-11 17:34 UTC by edouardparis

2021-05-14 14:09 UTC, danielabrozzoni requested changes

2021-05-14 15:26 UTC, danielabrozzoni commented
Also the commit message is missing a `~`, should be `~/.revault/revault_gui.toml`

2021-05-14 17:12 UTC, edouardparis commented on doc/DEMO.md
> +echo "revaultd_config_path=$(pwd)/revaultd/stake_1_config.toml" > revaultd/stake_1_config_ui.toml
I wanted to put it near the revaultd config toml, but I can move it to revault-gui

2021-05-17 14:08 UTC, danielabrozzoni approved these changes
ACK 1b48c64eb30f1c3338203e38966030f3051c4cc0

2021-05-17 16:58 UTC, merged