add revaultd::get_vaults
revault/revault-gui pull request #143
Opened 2021-06-10 14:34 UTC by edouardparis

Retrieve the vaults with a list of outpoints.
This fix the need to retrieve all vaults and filter
them by selected outpoints in the spend_transaction panel.

2021-06-10 14:38 UTC, danielabrozzoni requested changes
I'm not a fan of this honestly. It's not really clear why one function should be called `list_vaults` while the other one `get_vaults`, and it's not really consistent with `revaultd`, which just uses `listvaults` for everything. Why not modifying `list_vaults` for accepting both the outpoint and the statuses, exactly as revaultd does?

2021-06-11 09:32 UTC, danielabrozzoni commented
I absolutely don't see the point of having two different functions, it's redundant and confusing for someone whose comfortable with the revaultd api (why is a single function mapped to two different functions in the GUI?).

If you really want to have two different functions (and I'll repeat myself here: I don't think this is a good idea at all, it just makes things confusing) at least let's give them better names! It's not clear why one of the should be called `get` and the other one `list`, and there's no way anyone will remember that. Functions/variables names should be easy to remember or AT LEAST to guess, and `get` vs `list` is neither of them. You could instead use `list_vaults_status_filter` vs `list_vaults_outpoints_filter`, where at least one knows which function does what!

(But again, why should you do that? What's the problem in having a 'list_vaults' with two parameters?)


I'm sorry, I know I'm making a fuss around function names, but it's pretty clear that this change would make the code way more difficult to review and to write!

2021-06-14 14:21 UTC, edouardparis commented
Your comment made it very clear: better to have one method :+1: I will change that

2021-06-15 15:19 UTC, danielabrozzoni approved these changes
Cool! 😍 

ACK dacefc156e43e1d4e971ec8072730bd64bd6eea8

2021-06-15 15:31 UTC, merged